spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgres://elbhfgzqieizcw:f7c790e75ea49fdf947e5ced10bfd45ab3b52d97371468e3f1ed1012e441e252@ec2-52-1-115-6.compute-1.amazonaws.com:5432/d519qj7g93itdl?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driver-class-name: org.postgresql.Driver
    username: elbhfgzqieizcw
    password: f7c790e75ea49fdf947e5ced10bfd45ab3b52d97371468e3f1ed1012e441e252
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: INFO